# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

# Language and response settings
language: de
early_access: false
tone_instructions: "Professional, concise, and constructive. Focus on actionable feedback."

# Enable/disable features (optimized for Lite plan)
reviews:
  # Core review settings
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: false
  collapse_walkthrough: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "wip"
      - "draft"
      - "do not review"
      - "skip review"
    drafts: false
    base_branches:
      - main
      - develop

  # Path-based filters
  path_filters:
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/.astro/**"
    - "!**/coverage/**"
    - "!**/*.lock"
    - "!**/*.min.js"
    - "!**/*.min.css"

  path_instructions:
    - path: "src/components/**/*.vue"
      instructions: |
        - Verify Vue 3 Composition API usage (no Options API)
        - Check for proper TypeScript types in defineProps
        - Ensure client directives (client:visible, client:load) are used appropriately
        - Validate path aliases (@components, @layouts, @utils) are used instead of relative imports

    - path: "src/**/*.astro"
      instructions: |
        - Verify client directives are used appropriately (prefer client:visible)
        - Check Islands Architecture best practices
        - Ensure proper integration with Vue components
        - Validate SSG-friendly patterns

    - path: "**/*.{css,scss}"
      instructions: |
        - Verify Tailwind CSS v4 @theme usage for custom tokens
        - Check for proper CSS variable usage
        - Validate Lightning CSS compatibility
        - Ensure no @apply for one-off utilities

    - path: "**/*.{ts,tsx,js,jsx}"
      instructions: |
        - Verify TypeScript strict mode compliance
        - Check for proper error handling
        - Validate path aliases usage
        - Ensure no ESLint/TSLint, only OXC linter rules

    - path: "tests/**/*.spec.{ts,js}"
      instructions: |
        - Verify test coverage for critical paths
        - Check for proper test isolation
        - Validate Vitest/Playwright best practices
        - Ensure semantic selectors in E2E tests (aria-label, role, data-testid)

    - path: "**/*.config.{ts,js,mjs}"
      instructions: |
        - Verify configuration follows project conventions
        - Check for proper TypeScript types
        - Validate Vite+ inspired toolchain integration (Rolldown, OXC, Lightning CSS)

# Chat settings
chat:
  auto_reply: true

# Knowledge base - Project specific context
knowledge_base:
  # Enable learnings from conversation history
  learnings:
    scope: local # local = repo-only, global = org-wide, auto = smart default

  # Enable web search for additional context (defaults to enabled)
  web_search: {}

  # Code guidelines (automatically extracted from path_instructions above)
  code_guidelines:
    enabled: true
